# A dictionary to store characters and their stats
character_library = {
    "Azalea": {
        "initiative modifier": 3,
        "proficiency_bonus": 2,
        "armor_class": 14,
        "hit_pointelligences": 21,
        "strength": 13,
        "strength modifier": 1,
        "strength save": 1,
        "dexterity": 13,
        "dexterity modifier": 3,
        "dexterity save": 3,
        "constitution": 13,
        "constitution modifier": 1,
        "constitution save": 1,
        "intelligence": 13,
        "intelligence modifier": 1,
        "intelligence save": 1,
        "wisdom": 13,
        "wisdom modifier": 1,
        "wisdom save": 3,
        "charisma": 16,
        "charisma modifier": 4,
        "charisma save": 6,
        "inventory": []

    },
    "Gorwick": {
        "initiative modifier": 1,
        "proficiency_bonus": 2,
        "armor_class": 14,
        "hit_pointelligences": 36,
        "strength": 17,
        "strength modifier": 3,
        "strength save": 3,
        "dexterity": 13,
        "dexterity modifier": 1,
        "dexterity save": 1,
        "constitution": 14,
        "constitution modifier": 2,
        "constitution save": 2,
        "intelligence": 11,
        "intelligence modifier": 0,
        "intelligence save": 0,
        "wisdom": 14,
        "wisdom modifier": 2,
        "wisdom save": 4,
        "charisma": 10,
        "charisma modifier": 0,
        "charisma save": 2,
        "inventory": []
        
    },
    "Globius": {
        "initiative modifier": 1,
        "proficiency_bonus": 2,
        "armor_class": 11,
        "hit_pointelligences": 20,
        "strength": 12,
        "strength modifier": 1,
        "strength save": 1,
        "dexterity": 12,
        "dexterity modifier": 3,
        "dexterity save": 3,
        "constitution": 14,
        "constitution modifier": 2,
        "constitution save": 2,
        "intelligence": 18,
        "intelligence modifier": 4,
        "intelligence save": 6,
        "wisdom": 15,
        "wisdom modifier": 2,
        "wisdom save": 4,
        "charisma": 8,
        "charisma modifier": -1,
        "charisma save": -1,
        "inventory": []
        
    },
        "Klud": {
        "initiative modifier": 1,
        "proficiency_bonus": 2,
        "armor_class": 15,
        "hit_pointelligences": 32,
        "strength": 18,
        "strength modifier": 4,
        "strength save": 6,
        "dexterity": 12,
        "dexterity modifier": 1,
        "dexterity save": 1,
        "constitution": 14,
        "constitution modifier": 2,
        "constitution save": 4,
        "intelligence": 12,
        "intelligence modifier": 1,
        "intelligence save": 1,
        "wisdom": 11,
        "wisdom modifier": 0,
        "wisdom save": 0,
        "charisma": 7,
        "charisma modifier": -2,
        "charisma save": -2,
        "inventory": []
        
    },
        "Mesmir": {
        "initiative modifier": 4,
        "proficiency_bonus": 2,
        "armor_class": 15,
        "hit_pointelligences": 24,
        "strength": 15,
        "strength modifier": 2,
        "strength save": 2,
        "dexterity": 19,
        "dexterity modifier": 4,
        "dexterity save": 6,
        "constitution": 16,
        "constitution modifier": 3,
        "constitution save": 3,
        "intelligence": 12,
        "intelligence modifier": 0,
        "intelligence save": 2,
        "wisdom": 12,
        "wisdom modifier": 1,
        "wisdom save": 1,
        "charisma": 11,
        "charisma modifier": 0,
        "charisma save": 0,
        "inventory": []
        
    },
        "Rogath": {
        "initiative modifier": 2,
        "proficiency_bonus": 2,
        "armor_class": 16,
        "hit_pointelligences": 35,
        "strength": 19,
        "strength modifier": 4,
        "strength save": 6,
        "dexterity": 14,
        "dexterity modifier": 2,
        "dexterity save": 2,
        "constitution": 16,
        "constitution modifier": 3,
        "constitution save": 5,
        "intelligence": 18,
        "intelligence modifier": 4,
        "intelligence save": 4,
        "wisdom": 10,
        "wisdom modifier": 0,
        "wisdom save": 0,
        "charisma": 8,
        "charisma modifier": -1,
        "charisma save": -1,
        "inventory": []
        
    },
}

